package exports

import (
	"bytes"
	"fmt"
	"text/template"
)

const dockerRunTmplStr = `#!/usr/bin/env bash
# Generated by delightd
# Type: docker-run

exec docker run --rm -i \
  -v "$(pwd):{{ .Workdir }}" \
  -w "{{ .Workdir }}" \
  "{{ .Image }}" "$@"
`

const dockerExecTmplStr = `#!/usr/bin/env bash
# Generated by delightd
# Type: docker-exec

exec docker exec -i "{{ .Container }}" {{ .Command }} "$@"
`

var (
	dockerRunTmpl  = template.Must(template.New("docker-run").Parse(dockerRunTmplStr))
	dockerExecTmpl = template.Must(template.New("docker-exec").Parse(dockerExecTmplStr))
)

// GenerateWrapper produces the bash script string for a given docker export.
func GenerateWrapper(def ExportDef) (string, error) {
	var buf bytes.Buffer
	var err error

	switch def.Type {
	case TypeDockerRun:
		err = dockerRunTmpl.Execute(&buf, def)
	case TypeDockerExec:
		err = dockerExecTmpl.Execute(&buf, def)
	default:
		return "", fmt.Errorf("cannot generate wrapper for type %s", def.Type)
	}

	return buf.String(), err
}
