apiVersion: v1
kind: Service
metadata:
  name: surrealdb
  namespace: fleet
  labels:
    app.kubernetes.io/name: surrealdb
    app.kubernetes.io/part-of: fleet
spec:
  selector:
    app.kubernetes.io/name: surrealdb
  ports:
    - name: http
      port: 8000
      targetPort: http
